=== Tabrez911/Web_Basics/Xml_lab2/library.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


<!-- SIMPLE ELEMENTS -->
	 
	
	<xs:element name="Title" type="xs:string"/>
	<xs:element name="Author" type="xs:string"/>
	<xs:element name="Publisher" type="xs:string"/>
	<xs:element name="Cover" type="xs:string"/>
	<xs:element name="Category" type="xs:string"/>
	<xs:element name="ISBN" type="xs:string"/>
	<xs:element name="Rating" type="xs:positiveInteger"/>
	<xs:element name="Price" type="xs:decimal"/>
	<xs:element name="Comments" type="xs:string"/>
	
	<xs:attribute name="cover_type" type="xs:string"/>
	<xs:attribute name="cat_type" type="xs:string"/>
	<xs:attribute name="isbn_num" type="xs:string"/>
	<xs:attribute name="rate_val" type="xs:positiveInteger"/>
	
	

<!-- COMPLEX ELEMENTS -->

	<xs:element name="Book">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Title"/>
				<xs:element ref="Author"/>
				<xs:element ref="Publisher"/>
				<xs:element ref="Cover"/>
				<xs:element ref="Category"/>
				<xs:element ref="ISBN"/>
				<xs:element ref="Rating"/>
				<xs:element ref="Price"/>
				<xs:element ref="Comments"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name="library">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Book"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== Tabrez911/Web_Basics/Xml_lab2/library.xml
<?xml version="1.0" encoding="utf-8"?>

<library 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:noNamespaceSchemaLocation="library.xsd">
	
	<Book>
		<Title>Dead to the World</Title>
		<Author>Charlaine Harris</Author>
		<Publisher>ABC Publishing company</Publisher>
		<Cover cover_type="Hardbook"/>
		<Category cat_type="Horror"/>
		<ISBN isbn_num="Z1"/>
		<Rating rate_Val="5"/>
		<Price>$13.97</Price>
		<Comments>A good book</Comments>
	</Book>

	<Book>
		<Title>Gardens of the Moon </Title>
		<Author>Steven Erikson</Author>
		<Publisher>XYZ Publishers</Publisher>
		<Cover cover_type="Hardbook"></Cover>
		<Category cat_type="SCI-FI"></Category>
		<ISBN isbn_num="Z3"></ISBN>
		<Rating rate_Val="4"></Rating>
		<Price>$17.65</Price>
		<Comments>A wonderful book</Comments>
	</Book>
</library>
